/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RescheduleRouteImport } from './routes/reschedule'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingErrorRouteImport } from './routes/booking.error'
import { Route as BookingConfirmationRouteImport } from './routes/booking.confirmation'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RescheduleRoute = RescheduleRouteImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingErrorRoute = BookingErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => BookingRoute,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => BookingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/booking-success': typeof BookingSuccessRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reschedule': typeof RescheduleRoute
  '/services': typeof ServicesRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/error': typeof BookingErrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/booking-success': typeof BookingSuccessRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reschedule': typeof RescheduleRoute
  '/services': typeof ServicesRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/error': typeof BookingErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/booking-success': typeof BookingSuccessRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reschedule': typeof RescheduleRoute
  '/services': typeof ServicesRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/error': typeof BookingErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/booking-success'
    | '/contact'
    | '/doctors'
    | '/reschedule'
    | '/services'
    | '/booking/confirmation'
    | '/booking/error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/booking-success'
    | '/contact'
    | '/doctors'
    | '/reschedule'
    | '/services'
    | '/booking/confirmation'
    | '/booking/error'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/booking-success'
    | '/contact'
    | '/doctors'
    | '/reschedule'
    | '/services'
    | '/booking/confirmation'
    | '/booking/error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRouteWithChildren
  BookingSuccessRoute: typeof BookingSuccessRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  RescheduleRoute: typeof RescheduleRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reschedule': {
      id: '/reschedule'
      path: '/reschedule'
      fullPath: '/reschedule'
      preLoaderRoute: typeof RescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/error': {
      id: '/booking/error'
      path: '/error'
      fullPath: '/booking/error'
      preLoaderRoute: typeof BookingErrorRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof BookingRoute
    }
  }
}

interface BookingRouteChildren {
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  BookingErrorRoute: typeof BookingErrorRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingConfirmationRoute: BookingConfirmationRoute,
  BookingErrorRoute: BookingErrorRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRouteWithChildren,
  BookingSuccessRoute: BookingSuccessRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  RescheduleRoute: RescheduleRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
