// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env['SUPABASE_URL'];
  const SUPABASE_SERVICE_ROLE_KEY = process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    console.warn(
      `[Supabase] Service-role credentials unavailable (missing: ${missing.join(', ')}). ` +
        'Database-dependent features will be read-only. Connect Supabase in Lovable Cloud.',
    );
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | null | undefined;

/**
 * Safe no-op query chain used when the service-role key is missing.
 * Lets callers like readSetting/wireSetting resolve without throwing.
 */
function createAdminStub() {
  const emptyResult = { data: null, error: null };

  // Builder that is both chainable AND thenable (Supabase builders are awaitable).
  // When awaited, they resolve to { data, error }.
  const builderStub: Record<string, unknown> = {
    select: () => builderStub,
    eq: () => builderStub,
    order: () => builderStub,
    limit: () => builderStub,
    maybeSingle: () => Promise.resolve(emptyResult),
    upsert: () => Promise.resolve({ error: null }),
    delete: () => builderStub,
    insert: () => builderStub,
    // Make the builder itself awaitable — when Supabase callers do
    // `await db.from(x).select(...).eq(...)` or `await db.from(x).delete().eq(...)`
    // without .maybeSingle(), the builder resolves to { data: null, error: null }.
    then: (resolve: (v: unknown) => void) => Promise.resolve(emptyResult).then(resolve),
  };

  return {
    from: () => builderStub,
  };
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
type SupabaseAdminClient = NonNullable<ReturnType<typeof createSupabaseAdminClient>>;
export const supabaseAdmin = new Proxy({} as SupabaseAdminClient, {
  get(_, prop, receiver) {
    if (_supabaseAdmin === undefined) {
      _supabaseAdmin = createSupabaseAdminClient();
    }
    if (_supabaseAdmin === null) {
      // Graceful degradation: return a stub so .from(...).select() chains resolve to empty
      const stub = createAdminStub();
      return typeof stub[prop as keyof typeof stub] === 'function'
        ? stub[prop as keyof typeof stub]
        : Reflect.get(stub, prop, receiver);
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
